[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/app/entrypoint-railway.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = [
    "DATABASE_STRING",
    "OPENAI_API_KEY",
    "GEMINI_API_KEY",
    "ANTHROPIC_API_KEY",
    "BROWSER_TYPE=chromium-headless",
    "ENABLE_CODE_BLOCK=true",
    "PYTHONUNBUFFERED=1",
    "PYTHONDONTWRITEBYTECODE=1"
] 